version: "2"
services:
  workstand:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./bikeshop_project:/code
    volumes_from:
      - webpack
    environment:
      - PYTHONUNBUFFERED=0
  redis:
    restart: always
  db:
    restart: always
    environment:
            POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  webpack:
    build:
      context: .
      dockerfile: Dockerfile-webpack
    command: "npm run watch"
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - /code/node_modules
      - /code/vendor
      - ./bikeshop_project:/code:rw
